apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-node-viewer
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-node-viewer-binding
subjects:
  - kind: User
    name: kube
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kube-node-viewer
  apiGroup: rbac.authorization.k8s.io
